### ISSUE TITLE
Truncate labels

### ISSUE THREAD

**Issue by ULKARAMAKRISHNAN** [rviscomi/trunk8#69]
Hi,

I am trying to truncate text inside labels. But its clearing off all the texts instead of just truncating.

Any help would be great.

Thanks

**Comment by rviscomi** [comment]
Could you make a js fiddle demonstrating your issue?

**Comment by ULKARAMAKRISHNAN** [comment]
https://jsfiddle.net/nuggm16d/
You can have a look at the issue in the above fiddle.

I figured out the prob here and fixed it. The line height of 9px was causing the issue. But not sure why was it causing the prob. 

Curious to know the reason behind it.

Thanks

**Comment by rviscomi** [comment]
The issue is that you are forcing the line height of the LI element to 9px. At the same time, you're using DIVs for both the radio button and the truncated label. DIVs are block-level by default, so they each take up their own line. By forcing the line-height to 9px, you're cutting off the second DIV containing the label. So the text is being truncated properly but you're hiding it by masking the contents of the LI.

**Comment by ULKARAMAKRISHNAN** [comment]
Even I thought of it but then when I inspect I dont see the text being truncated. It is totally blank.

**Comment by rviscomi** [comment]
Just make the line-height fit the text (16px).

**Comment by ULKARAMAKRISHNAN** [comment]
Thanks. It works.
